import React from "react";
import { storiesOf } from "@storybook/react";
import Image from "./";

storiesOf("Image", module)
  .add("SevenUpspot", () => <img src={Image.SevenUpspot} />)
  .add("Americanflag", () => <img src={Image.Americanflag} />)
  .add("Community", () => <img src={Image.Community} />)
  .add("Computer01", () => <img src={Image.Computer01} />)
  .add("Computer", () => <img src={Image.Computer} />)
  .add("Construction", () => <img src={Image.Construction} />)
  .add("Counter", () => <img src={Image.Counter} />)
  .add("Counter2", () => <img src={Image.Counter2} />)
  .add("Divider1", () => <img src={Image.Divider1} />)
  .add("Divider2", () => <img src={Image.Divider2} />)
  .add("Divider3", () => <img src={Image.Divider3} />)
  .add("Divider4", () => <img src={Image.Divider4} />)
  .add("Drudgesiren", () => <img src={Image.Drudgesiren} />)
  .add("Emailme", () => <img src={Image.Emailme} />)
  .add("Flames", () => <img src={Image.Flames} />)
  .add("Funky", () => <img src={Image.Funky} />)
  .add("Geocities", () => <img src={Image.Geocities} />)
  .add("GlyphiconsHalflingsWhite", () => (
    <img src={Image.GlyphiconsHalflingsWhite} />
  ))
  .add("GlyphiconsHalflings", () => <img src={Image.GlyphiconsHalflings} />)
  .add("Hacker", () => <img src={Image.Hacker} />)
  .add("Heart", () => <img src={Image.Heart} />)
  .add("Hot", () => <img src={Image.Hot} />)
  .add("IELogo", () => <img src={Image.IELogo} />)
  .add("Mailkitten", () => <img src={Image.Mailkitten} />)
  .add("Mchammer", () => <img src={Image.Mchammer} />)
  .add("Microfab", () => <img src={Image.Microfab} />)
  .add("New", () => <img src={Image.New} />)
  .add("New2", () => <img src={Image.New2} />)
  .add("Noframes", () => <img src={Image.Noframes} />)
  .add("Notepad", () => <img src={Image.Notepad} />)
  .add("Progress", () => <img src={Image.Progress} />)
  .add("Rrainbow", () => <img src={Image.Rrainbow} />)
  .add("SignIn", () => <img src={Image.SignIn} />)
  .add("Spinningearth", () => <img src={Image.Spinningearth} />)
  .add("Stars", () => <img src={Image.Stars} />)
  .add("Underconstruction", () => <img src={Image.Underconstruction} />)
  .add("Wabwalk", () => <img src={Image.Wabwalk} />)
  .add("Webtrips", () => <img src={Image.Webtrips} />)
  .add("Yahooweek", () => <img src={Image.Yahooweek} />);
