name: DEV

on:
  push:
    branches:
      - "*"
      - "*/*"
      - "**"
      - "!master"

jobs:
  release:
    name: check version, add tag and release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          registry-url: "https://registry.npmjs.org"
      - name: install
        run: yarn install
      - name: lint
        run: yarn run lint:ci
      - name: format
        run: yarn run format:ci
      - name: build
        run: yarn run lib build
      - name: build
        run: yarn run lib build-storybook
      - name: typecheck
        run: yarn run typecheck
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_RE_GEO }}"
          projectId: re-geo
          channelId: "pr-${{ github.event.number }}-${{ github.event.pull_request.head.ref }}"
